### ISSUE TITLE
about 戦甲's translation

### ISSUE THREAD

**Issue by ElFakirZakaria** [riftcrystal/DDON-Translation#26]
just found 戦甲砕きのクレスト = senko kudaki no cresto
戦甲ゴアサイクロプス = senko goacyclopsu 
kudaki = means breaking, so it's crest of armor break in my opinion.
just don't want see war-ready break crest for the sake of consistency 
i believe we should adapt senko 戦甲 as armor for future translation and have Armored Gorecyclops instead of War-ready Gorecyclops for example.

Hope to get many opinions and close this issue soon.

**Comment by riftcrystal** [comment]
The crest could be better named, sure. The official romanization for the enemies is War-Ready.

There is also the fact that there is an enemy modifier (like infected) for armored.
