### ISSUE TITLE
Patch needs updating. Names on Items, Gems, etc.

### ISSUE THREAD

**Issue by KaiserCainhurst** [riftcrystal/DDON-Translation#43]
As of right now the current patch breaks anything related to in-game craft items, rings, gems and so on.
As an example Rookie ring is now a "Ring of Physical Attack 1" with the passive of "Beast-Steak.1074"
The patch is also reported to have been preventing event NPC from appearing.

If you don't wish to continue with the updates, please open source your method.

**Comment by ElementNone** [comment]
Thank you for all your work riftcrystal! Your patches make an amazing game even more enjoyable! Please let the community know if you need someone to take over! I am sure they will rise up to the challenge.

**Comment by jeffmounce** [comment]
Yes, we can definitely continue. I'd be willing to do it if you can provide some direction.

**Comment by riftcrystal** [comment]
It's combination of being busy over holidays, and losing my copies of the game due to corruption. I'm in the process of redownloading.

A release for newer patch will be available once I can get to it.
