### ISSUE TITLE
Regarding cut-scenes

### ISSUE THREAD

**Issue by Lasria** [riftcrystal/DDON-Translation#62]
Wanted to make sure with you that translating cut-scenes is alright. I remember someone in the discord saying it wasn't possible but some of the scenes are already tl'd aren't they? Also want to make sure they follow the same format etc.

**Comment by riftcrystal** [comment]
That's fine, the only limitation is there's no way to currently edit message timing during cutscenes. If there is an actual interest in translating cutscenes I could look into making it possible.

**Comment by Lasria** [comment]
I'm not sure if changing message timing is strictly necessary. I'll try doing some scenes and see how it goes.
